### ISSUE TITLE
how to get the npy file of w_plus?

### ISSUE THREAD

**Issue by snow1929** [betterze/StyleAlign#13]
how to get the npy file of w_plus?

**Comment by betterze** [comment]
We use [e4e encoder](https://github.com/omertov/encoder4editing) to invert real images into w+ space. We provide pretrained e4e models for FFHQ512, FFHQ512_dog, FFHQ512_dog_cat in [here](https://drive.google.com/drive/folders/1MqCHQ6Yx-eon-3fu1g_AGjpyAUmzH6Jy).

Please clone the [e4e repo](https://github.com/omertov/encoder4editing) and download the [pretrained models](https://drive.google.com/drive/folders/1MqCHQ6Yx-eon-3fu1g_AGjpyAUmzH6Jy), and run

```
python scripts/inference.py \
--images_dir=/path/to/images/directory \
--save_dir=/path/to/saving/directory \
path/to/checkpoint.pt 
```

in e4e folder. The w_plus latent codes will be in the save_dir. Then you just need to save the torch file to npy file.

**Comment by snow1929** [comment]
@betterze 
Thanks you for explaining the code of model.
As I try to run the code
There is an error happened.
But I have no idea how to fix it.
Would you please give me some suggestion for dealing it ?
```
python3 projector_z.py --outdir=./example/dog/  --target=./example/dog/ --network=./checkpoint/ffhq512_dog.pkl
```
![image](https://user-images.githubusercontent.com/42559501/192449642-153eeeb8-ed0f-45b7-b961-bdcc19a7bfde.png)

**Comment by snow1929** [comment]
I run the sample code on colab
And the error of tensor is happend
Is there anything wrong?
![image](https://user-images.githubusercontent.com/42559501/192684556-f9fd5b9e-4565-4bd0-9c58-2ed45662638c.png)

**Comment by betterze** [comment]
@snow1929 which tensorflow version you are using? I use 1.14

**Comment by snow1929** [comment]
I use tensorflow 1.15
![image](https://user-images.githubusercontent.com/42559501/192709920-3267c1c6-da4b-474c-a17b-6aecd944426a.png)
I try to change the version of tensorflow and run it again.
thank you

**Comment by betterze** [comment]
> I run the sample code on colab And the error of tensor is happend Is there anything wrong? ![image](https://user-images.githubusercontent.com/42559501/192684556-f9fd5b9e-4565-4bd0-9c58-2ed45662638c.png)

This error is related to the environment (gcc). Pls install the environment following [stylegan2-ada](https://github.com/NVlabs/stylegan2-ada#requirements).

**Comment by snow1929** [comment]
Hi @betterze ,
I have already check the source of image.
All of the image is 512x512.
Thus, I have no idea how to fix this trouble.

![image](https://user-images.githubusercontent.com/42559501/193399646-7a79008a-45b6-44e9-89b6-9f98382d8f5f.png)
```
Traceback (most recent call last):
  File "Compare.py", line 89, in <module>
    main()
  File "Compare.py", line 79, in main
    out=np.concatenate([imgs,invert,target],axis=1)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 512 and the array at index 2 has size 256
```

**Comment by betterze** [comment]
Would you mind printing the shape of [imgs,invert,target] separately?

**Comment by snow1929** [comment]
```
name = ['flickr_dog_000043.jpg', 'flickr_dog_000045.jpg', 'flickr_dog_000054.jpg', 'flickr_dog_000059.jpg']
imgs_shape= (512, 512, 3)
invert_shape= (512, 512, 3)
target_shape= (256, 256, 3)
```
![image](https://user-images.githubusercontent.com/42559501/193404198-f25e8a18-68e5-491b-b640-fec888e5b88c.png)

**Comment by betterze** [comment]
The target images are in shape (256,256), rather than (512, 512). So it causes the error.

**Comment by betterze** [comment]
Which target model (target_pkl) you are using?

**Comment by snow1929** [comment]
I choose the model of "stylegan2-ffhq512_dog_cat-config-f.pkl" as target_pkl!!
![image](https://user-images.githubusercontent.com/42559501/193409344-c7930757-5bbe-44e6-89ab-74de01a6b782.png)

**Comment by betterze** [comment]
The images in the target_path are in (256, 256), could you doublecheck this. Go to the folder and check the image size. 

Remove all images in the target_path, and rerun 

```
python I2I.py --network $target_pkl \
  	      --source_path $source_path \
  	      --target_path $target_path	


python Compare.py --source_img_path $source_img_path \
  	      --source_path $source_path \
  	      --target_path $target_path \
  	      --save_path $compare_html 
```

**Comment by snow1929** [comment]
there is a pkl file be downloaded before I start to translate imge to laten type
what the purpose to download this file
"https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada/pretrained/metrics/vgg16_zhang_perceptual.pkl"
![image](https://user-images.githubusercontent.com/42559501/197142743-b3eab610-162f-43c3-b7a3-fc87a6369991.png)

**Comment by snow1929** [comment]
@betterze 
If I want to use [e4e encoder](https://github.com/omertov/encoder4editing) to invert real images into w+ space with my own dataset.

how to get "checkpoint.pt" 

I have to finished the prtrained model by [e4e encoder]?
Or, can I invert the [stylegan-ada](https://github.com/NVlabs/stylegan2-ada.git) prtrained model to pt filetype?
how to do it?

**Comment by snow1929** [comment]
I find the way to invert pkl to pt filetype/
Thank you.

https://github.com/omertov/encoder4editing/issues/64
